"""Metalium C++ emitter for the frozen overnight protocol subset (v1).

Emits a practical host program + ONE data-movement RISC-V kernel that execute
a protocol program validated by the native checker
(specializations/tenstorrent_protocol/protocol.py) on one Blackhole Tensix
core: one CB per slot, one page per CB, raw uint8 page copies through DRAM
page accessors and CB actual pointers.  No SFPU, no format conversion.

Derived from the official tt-metal examples at pinned commit
ad232e1cd799adf53841774805bc73fc5605b634:
- tt_metal/programming_examples/loopback/loopback.cpp            (MeshDevice/
  MeshBuffer/TensorAccessorArgs/EnqueueMeshWorkload host flow)
- tt_metal/programming_examples/loopback/kernels/loopback_dram_copy.cpp
  (device TensorAccessor + noc_async_* page copies)
- tt_metal/programming_examples/contributed/vecadd/kernels/interleaved_tile_read.cpp
  (CB lifecycle: cb_reserve_back / get_write_ptr / barrier / cb_push_back /
  cb_wait_front / get_read_ptr / barrier / cb_pop_front)
- tt_metal/programming_examples/loopback/CMakeLists.txt          (standalone
  find_package(TT-Metalium) build)

Op-to-kernel-call mapping (single issuer, single NoC; NoC barriers cover the
whole outstanding queue of the issuing NoC, which for this subset equals the
contract's pending queue of the matching direction):
  reserve    -> cb_reserve_back(cb_slot, 1)
  read       -> get_write_ptr(cb_slot); noc_async_read(src_acc.get_noc_addr(src), wptr, page_bytes)
  wait_reads -> noc_async_read_barrier()
  publish    -> cb_push_back(cb_slot, 1)
  acquire    -> cb_wait_front(cb_slot, 1)
  write      -> get_read_ptr(cb_slot); noc_async_write(rptr, dst_acc.get_noc_addr(dst), page_bytes)
  wait_writes-> noc_async_write_barrier()
  release    -> cb_pop_front(cb_slot, 1)
"""

from __future__ import annotations

import dataclasses

from specializations.tenstorrent_protocol import protocol

# Flat 3-word instruction encoding consumed by the kernel switch:
# [opcode, arg0, arg1]; unused args are 0.
OPCODES = {
    "reserve": 0,
    "read": 1,
    "wait_reads": 2,
    "publish": 3,
    "acquire": 4,
    "write": 5,
    "wait_writes": 6,
    "release": 7,
}
OP_ARGS = {
    "reserve": ("slot", 0),
    "read": ("slot", "src"),
    "wait_reads": (0, 0),
    "publish": ("slot", 0),
    "acquire": ("slot", 0),
    "write": ("slot", "dst"),
    "wait_writes": (0, 0),
    "release": ("slot", 0),
}


def op_to_dict(op) -> dict:
    """Canonical dict form of a protocol IR op."""
    if isinstance(op, dict):
        return op
    d = {"op": op.op}
    d.update(protocol._op_fields_dict(op))
    return d


def encode_program(program) -> list[int]:
    """Program -> flat [op, arg0, arg1] triples (kernel runtime-arg stream)."""
    words: list[int] = []
    for op in program:
        d = op_to_dict(op)
        a0, a1 = OP_ARGS[d["op"]]
        words += [OPCODES[d["op"]], d.get(a0, 0) if isinstance(a0, str) else a0,
                  d.get(a1, 0) if isinstance(a1, str) else a1]
    return words


def decode_program(words) -> list[dict]:
    """Inverse of encode_program; used to bind emitted artifacts back to the
    protocol IR (tests decode the emitted host table and re-check it)."""
    if len(words) % 3 != 0:
        raise ValueError(f"encoded program must be a multiple of 3 words, got {len(words)}")
    inv = {v: k for k, v in OPCODES.items()}
    out = []
    for i in range(0, len(words), 3):
        opc, a0, a1 = words[i : i + 3]
        if opc not in inv:
            raise ValueError(f"unknown opcode {opc} at instruction {i // 3}")
        name = inv[opc]
        f0, f1 = OP_ARGS[name]
        d = {"op": name}
        if isinstance(f0, str):
            d[f0] = a0
        if isinstance(f1, str):
            d[f1] = a1
        out.append(d)
    return out


def _cpp_uint_list(words, per_line=8) -> str:
    rows = []
    for i in range(0, len(words), per_line):
        rows.append("    " + ", ".join(f"{w}u" for w in words[i : i + per_line]) + ",")
    return "\n".join(rows).rstrip(",")


KERNEL_TEMPLATE = """\
// SPDX-FileCopyrightText: VeriTac overnight runtime worker
// SPDX-License-Identifier: Apache-2.0
//
// Generated by specializations/tenstorrent_protocol/runtime/emit_cpp.py.
// ONE data-movement kernel on one Tensix core (Blackhole), RISCV_0 / NOC_0.
// Executes the validated protocol program word stream from runtime args.
// Raw uint8 page copies only: DRAM page accessor + CB actual pointers.
// No SFPU, no data-format conversion.

#include <cstdint>

#include "api/dataflow/dataflow_api.h"

// [opcode, arg0, arg1] triples; mirrors emit_cpp.OPCODES.
constexpr uint32_t OP_RESERVE = {reserve};
constexpr uint32_t OP_READ = {read};
constexpr uint32_t OP_WAIT_READS = {wait_reads};
constexpr uint32_t OP_PUBLISH = {publish};
constexpr uint32_t OP_ACQUIRE = {acquire};
constexpr uint32_t OP_WRITE = {write};
constexpr uint32_t OP_WAIT_WRITES = {wait_writes};
constexpr uint32_t OP_RELEASE = {release};

// TensorAccessorArgs compile-time args are appended by the host from the
// actual MeshBuffers (input first, output second), as in the official
// loopback example.
constexpr auto kSrcArgs = TensorAccessorArgs<0>();
constexpr auto kDstArgs = TensorAccessorArgs<kSrcArgs.next_compile_time_args_offset()>();

void kernel_main() {{
    const uint32_t src_base = get_arg_val<uint32_t>(0);
    const uint32_t dst_base = get_arg_val<uint32_t>(1);
    const uint32_t page_bytes = get_arg_val<uint32_t>(2);
    const uint32_t n_instr = get_arg_val<uint32_t>(3);

    const auto src_acc = TensorAccessor(kSrcArgs, src_base, page_bytes);
    const auto dst_acc = TensorAccessor(kDstArgs, dst_base, page_bytes);

    constexpr uint32_t cb_base = {{static_cast<uint32_t>(tt::CBIndex::c_0)}};
    const uint32_t* instr = reinterpret_cast<const uint32_t*>(get_arg_addr(4));

    for (uint32_t pc = 0; pc < n_instr; ++pc) {{
        const uint32_t opcode = instr[pc * 3 + 0];
        const uint32_t a0 = instr[pc * 3 + 1];
        const uint32_t a1 = instr[pc * 3 + 2];
        const uint32_t cb = cb_base + a0;
        switch (opcode) {{
        case OP_RESERVE:
            // slot phase: free -> reserved (one free page reserved in CB)
            cb_reserve_back(cb, 1);
            break;
        case OP_READ:
            // issue async DRAM page read into the reserved CB page;
            // completion fills the slot value (origin = src page)
            {{
                const uint32_t wptr = get_write_ptr(cb);
                const uint64_t src = src_acc.get_noc_addr(a1);
                noc_async_read(src, wptr, page_bytes);
            }}
            break;
        case OP_WAIT_READS:
            // BLOCKING: all outstanding NoC reads complete before proceeding
            noc_async_read_barrier();
            break;
        case OP_PUBLISH:
            // reserved -> published (reader side may now see the page)
            cb_push_back(cb, 1);
            break;
        case OP_ACQUIRE:
            // published -> acquired (blocks until the page is visible)
            cb_wait_front(cb, 1);
            break;
        case OP_WRITE:
            // issue async CB page write to the DRAM destination page
            {{
                const uint32_t rptr = get_read_ptr(cb);
                const uint64_t dst = dst_acc.get_noc_addr(a1);
                noc_async_write(rptr, dst, page_bytes);
            }}
            break;
        case OP_WAIT_WRITES:
            // BLOCKING: all outstanding NoC writes complete
            noc_async_write_barrier();
            break;
        case OP_RELEASE:
            // acquired -> free (page leaves the CB; safe after write barrier
            // and with no pending transfer on the slot, per protocol)
            cb_pop_front(cb, 1);
            break;
        default:
            // Unreachable for validated programs; trap loudly if ever hit.
            ASSERT(false);
            break;
        }}
    }}
}}
"""

INPUT_GEN_TEMPLATE = """\
// SPDX-FileCopyrightText: VeriTac overnight runtime worker
// SPDX-License-Identifier: Apache-2.0
//
// Deterministic input fill + FNV-1a 64 checksum.  Kept free of tt-metalium
// includes so tests can compile and evaluate it standalone and compare with
// the Python runner reference.  Keep byte-exact parity with runner.py.

#pragma once

#include <cstddef>
#include <cstdint>
#include <vector>

// 32-bit LCG (Numerical Recipes constants); byte = bits [31:24].
inline void veritac_fill_input(std::vector<uint8_t>& out, uint32_t seed = 0x12345678u) {
    uint32_t x = seed;
    for (auto& b : out) {
        x = 1664525u * x + 1013904223u;
        b = static_cast<uint8_t>(x >> 24);
    }
}

inline uint64_t veritac_fnv1a64(const uint8_t* p, size_t n) {
    uint64_t h = 14695981039346656037ull;  // FNV-1a offset basis
    for (size_t i = 0; i < n; ++i) {
        h ^= p[i];
        h *= 1099511628211ull;  // FNV-1a prime
    }
    return h;
}
"""

HOST_TEMPLATE = """\
// SPDX-FileCopyrightText: VeriTac overnight runtime worker
// SPDX-License-Identifier: Apache-2.0
//
// Generated by specializations/tenstorrent_protocol/runtime/emit_cpp.py.
// Host driver: deterministic full input fill, sentinel-filled outputs,
// one-DM-kernel protocol program on one Blackhole Tensix core via a unit
// MeshDevice, read-back and bit-for-bit compare against the expected page
// mapping (output page d == input page expected[d]).

#include <cstdint>
#include <cstring>
#include <fstream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

#include <fmt/core.h>
#include <tt-metalium/host_api.hpp>
#include <tt-metalium/device.hpp>
#include <tt-metalium/distributed.hpp>
#include <tt-metalium/tensor_accessor_args.hpp>

#include "input_gen.hpp"

using namespace tt::tt_metal;

namespace {{
constexpr uint32_t kInputPages = {input_pages}u;
constexpr uint32_t kOutputPages = {output_pages}u;
constexpr uint32_t kSlots = {slots}u;
constexpr uint32_t kPageBytes = {page_bytes}u;
constexpr uint32_t kSeed = 0x12345678u;
constexpr uint8_t kSentinel = 0xA5u;

// expected[d] = source input page of output page d
constexpr uint32_t kExpected[kOutputPages] = {{
{expected_body}
}};

// Validated protocol program as [op, arg0, arg1] triples (emit_cpp encoding).
constexpr uint32_t kProgramLen = {n_instr}u;
constexpr uint32_t kProgram[3u * kProgramLen] = {{
{program_body}
}};
}}  // namespace

int main(int argc, char** argv) {{
    // 1x1 mesh: one Blackhole device, one Tensix core {{0,0}}, one DM kernel.
    std::shared_ptr<distributed::MeshDevice> mesh_device;
    bool pass = true;

    try {{
        const uint64_t seed_arg = argc > 1 ? std::stoull(argv[1]) : kSeed;
        if (seed_arg > std::numeric_limits<uint32_t>::max()) throw std::runtime_error("seed out of range");
        const uint32_t seed = static_cast<uint32_t>(seed_arg);
        const std::string pattern = argc > 2 ? argv[2] : "lcg";
        mesh_device = distributed::MeshDevice::create_unit_mesh(0);
        distributed::MeshCommandQueue& cq = mesh_device->mesh_command_queue();
        const uint32_t in_bytes = kInputPages * kPageBytes;
        const uint32_t out_bytes = kOutputPages * kPageBytes;

        // Disjoint DRAM buffers, one page per DRAM page accessor step.
        distributed::DeviceLocalBufferConfig dram_config{{
            .page_size = kPageBytes, .buffer_type = tt::tt_metal::BufferType::DRAM}};
        distributed::ReplicatedBufferConfig in_cfg{{.size = in_bytes}};
        distributed::ReplicatedBufferConfig out_cfg{{.size = out_bytes}};
        auto input_dram_buffer =
            distributed::MeshBuffer::create(in_cfg, dram_config, mesh_device.get());
        auto output_dram_buffer =
            distributed::MeshBuffer::create(out_cfg, dram_config, mesh_device.get());

        Program program = CreateProgram();
        constexpr CoreCoord core = {{0, 0}};

        // One CB per slot, exactly one page each; distinct slots are disjoint
        // L1 regions by construction. Raw UInt8 pages, no format conversion.
        for (uint32_t s = 0; s < kSlots; ++s) {{
            const uint32_t cb_index = static_cast<uint32_t>(tt::CBIndex::c_0) + s;
            CircularBufferConfig cb_config(kPageBytes,
                {{{{cb_index, tt::DataFormat::UInt8}}}});
            cb_config.set_page_size(cb_index, kPageBytes);
            CreateCircularBuffer(program, core, cb_config);
        }}

        // DRAM page accessors bound to the actual buffers (TensorAccessorArgs
        // compile-time args, as in the official loopback example).
        std::vector<uint32_t> compile_args;
        TensorAccessorArgs(*input_dram_buffer->get_backing_buffer()).append_to(compile_args);
        TensorAccessorArgs(*output_dram_buffer->get_backing_buffer()).append_to(compile_args);
        const std::string kernel_dir = VERITAC_KERNEL_DIR;
        KernelHandle kernel_id = CreateKernel(
            program, kernel_dir + "/dm_slot_copy.cpp", core,
            DataMovementConfig{{
                .processor = DataMovementProcessor::RISCV_0,
                .noc = NOC::RISCV_0_default,
                .compile_args = compile_args}});

        // Deterministic full input; deterministic sentinel-filled outputs.
        std::vector<uint8_t> input(in_bytes);
        veritac_fill_input(input, seed);
        if (pattern == "zero" || pattern == "ones" || pattern == "alternating") {{
            for (size_t i = 0; i < input.size(); ++i) {{
                input[i] = pattern == "zero" ? 0 : pattern == "ones" ? 255 : (i % 2 == 0 ? 170 : 85);
            }}
        }} else if (pattern != "lcg") throw std::runtime_error("unknown input pattern");
        std::vector<uint8_t> out_sentinel(out_bytes, kSentinel);

        // Host CPU reference: output page d must equal input page kExpected[d].
        std::vector<uint8_t> expected_out(out_bytes);
        for (uint32_t d = 0; d < kOutputPages; ++d) {{
            std::memcpy(expected_out.data() + d * kPageBytes,
                        input.data() + kExpected[d] * kPageBytes, kPageBytes);
        }}
        const uint64_t in_sum = veritac_fnv1a64(input.data(), input.size());
        const uint64_t exp_sum = veritac_fnv1a64(expected_out.data(), expected_out.size());

        if (input_dram_buffer->address() > std::numeric_limits<uint32_t>::max() ||
            output_dram_buffer->address() > std::numeric_limits<uint32_t>::max()) {{
            throw std::runtime_error("DRAM base exceeds supported 32-bit accessor base");
        }}
        // 4 scalar runtime args, then the flat [op, arg0, arg1] word stream.
        std::vector<uint32_t> runtime_args = {{
            static_cast<uint32_t>(input_dram_buffer->address()),
            static_cast<uint32_t>(output_dram_buffer->address()),
            kPageBytes, kProgramLen}};
        for (const uint32_t w : kProgram) runtime_args.push_back(w);
        SetRuntimeArgs(program, kernel_id, core, runtime_args);

        distributed::EnqueueWriteMeshBuffer(cq, input_dram_buffer, input, /*blocking=*/true);
        distributed::EnqueueWriteMeshBuffer(cq, output_dram_buffer, out_sentinel, /*blocking=*/true);

        distributed::MeshWorkload workload;
        distributed::MeshCoordinateRange device_range =
            distributed::MeshCoordinateRange(mesh_device->shape());
        workload.add_program(device_range, std::move(program));
        distributed::EnqueueMeshWorkload(cq, workload, /*blocking=*/false);
        distributed::Finish(cq);

        std::vector<uint8_t> result;
        distributed::EnqueueReadMeshBuffer(cq, result, output_dram_buffer, /*blocking=*/true);

        if (result.size() != out_bytes) {{
            fmt::print("VERIFY FATAL: read back {{}} bytes, want {{}}\\n", result.size(), out_bytes);
            mesh_device->close();
            return 1;
        }}

        std::ofstream output_file("output.bin", std::ios::binary);
        output_file.write(reinterpret_cast<const char*>(result.data()), result.size());
        output_file.close();
        if (!output_file) throw std::runtime_error("cannot save full output bytes");
        // Exact compare, page by page, against the CPU reference mapping.
        for (uint32_t d = 0; d < kOutputPages; ++d) {{
            const uint8_t* got = result.data() + d * kPageBytes;
            const uint8_t* want = expected_out.data() + d * kPageBytes;
            if (std::memcmp(got, want, kPageBytes) != 0) {{
                pass = false;
                uint32_t off = 0;
                while (off + 1 < kPageBytes && got[off] == want[off]) ++off;
                fmt::print("PAGE MISMATCH: dst={{}} expected_src={{}} first_diff_offset={{}} "
                           "got={{:#04x}} want={{:#04x}}\\n",
                           d, kExpected[d], off, got[off], want[off]);
            }}
        }}

        const uint64_t got_sum = veritac_fnv1a64(result.data(), result.size());
        fmt::print("INPUT_CHECKSUM {{:016x}}\\n", in_sum);
        fmt::print("EXPECTED_OUTPUT_CHECKSUM {{:016x}}\\n", exp_sum);
        fmt::print("OUTPUT_CHECKSUM {{:016x}}\\n", got_sum);
        fmt::print("PAGES {{}} input_pages={{}} output_pages={{}} slots={{}} page_bytes={{}}\\n",
                   kOutputPages, kInputPages, kOutputPages, kSlots, kPageBytes);
        if (pass) {{
            fmt::print("VERIFY OK {{}}\\n", kOutputPages);
        }} else {{
            fmt::print("VERIFY FAIL\\n");
        }}
    }} catch (const std::exception& e) {{
        fmt::print(stderr, "FATAL exception: {{}}\\n", e.what());
        if (mesh_device) mesh_device->close();
        return 1;
    }}

    if (!mesh_device->close()) {{
        return 1;
    }}
    return pass ? 0 : 1;
}}
"""

CMAKE_TEMPLATE = """\
# Generated by specializations/tenstorrent_protocol/runtime/emit_cpp.py.
# Two build modes:
#   1. package: find_package(TT-Metalium) against an installed/built tt-metal
#      (pass -DCMAKE_PREFIX_PATH=<prefix>, e.g. /opt/tt/install)
#   2. add_subdirectory: pass -DTT_METAL_SOURCE=<tt-metal checkout>
cmake_minimum_required(VERSION 3.22...4.2)
project(veritac_tt_protocol CXX)

add_executable(veritac_tt_protocol host_main.cpp)
target_include_directories(veritac_tt_protocol PRIVATE ${{CMAKE_CURRENT_SOURCE_DIR}})
target_compile_definitions(veritac_tt_protocol PRIVATE
    VERITAC_KERNEL_DIR="${{CMAKE_CURRENT_SOURCE_DIR}}/kernels")

if(NOT TARGET TT::Metalium)
    if(TT_METAL_SOURCE)
        add_subdirectory(${{TT_METAL_SOURCE}} ${{CMAKE_BINARY_DIR}}/tt-metal EXCLUDE_FROM_ALL)
    else()
        find_package(TT-Metalium REQUIRED)
    endif()
endif()
target_link_libraries(veritac_tt_protocol PUBLIC TT::Metalium)
if(TARGET TT::CommonPCH)
    tt_reuse_precompile_headers(veritac_tt_protocol TT::CommonPCH)
endif()
"""


def emit_kernel() -> str:
    return KERNEL_TEMPLATE.format(**OPCODES)


def emit_input_gen() -> str:
    return INPUT_GEN_TEMPLATE


def emit_host(task: protocol.Task, program) -> str:
    program = tuple(program)
    if 4 + 3 * len(program) > 341:
        raise ValueError('program exceeds pinned Metalium 341-word runtime argument capacity (112 instructions)')
    expected_body = _cpp_uint_list(list(task.expected))
    program_body = _cpp_uint_list(encode_program(program))
    return HOST_TEMPLATE.format(
        input_pages=task.input_pages,
        output_pages=len(task.expected),
        slots=task.slots,
        page_bytes=task.page_bytes,
        expected_body=expected_body,
        n_instr=len(tuple(program)),
        program_body=program_body,
    )


def emit_cmake() -> str:
    return CMAKE_TEMPLATE.format()


def emit_bundle(task: protocol.Task, proposal: protocol.Proposal) -> dict[str, str]:
    """Relative path -> file content for a complete buildable bundle."""
    return {
        "host_main.cpp": emit_host(task, proposal.program),
        "input_gen.hpp": emit_input_gen(),
        "kernels/dm_slot_copy.cpp": emit_kernel(),
        "CMakeLists.txt": emit_cmake(),
        "task.json": task_to_dict_json(task),
        "proposal.json": proposal_to_dict_json(proposal),
    }


def _task_to_dict(task: protocol.Task) -> dict:
    return {
        "id": task.id,
        "input_pages": task.input_pages,
        "expected": list(task.expected),
        "slots": task.slots,
        "page_bytes": task.page_bytes,
    }


task_to_dict = _task_to_dict


def _proposal_to_dict(proposal: protocol.Proposal) -> dict:
    return {
        "program": [op_to_dict(op) for op in proposal.program],
        "rationale": proposal.rationale,
    }


proposal_to_dict = _proposal_to_dict


def _json_dump(obj: dict) -> str:
    import json

    return json.dumps(obj, indent=2) + "\n"


def task_to_dict_json(task: protocol.Task) -> str:
    return _json_dump(_task_to_dict(task))


def proposal_to_dict_json(proposal: protocol.Proposal) -> str:
    return _json_dump(_proposal_to_dict(proposal))


__all__ = [
    "OPCODES",
    "OP_ARGS",
    "encode_program",
    "decode_program",
    "op_to_dict",
    "task_to_dict",
    "proposal_to_dict",
    "task_to_dict_json",
    "proposal_to_dict_json",
    "emit_kernel",
    "emit_input_gen",
    "emit_host",
    "emit_cmake",
    "emit_bundle",
]
